### PR TITLE
first draft of branching/merging-concept

### PR DESCRIPTION
**Pull request by ibogicevic**

### CODE REVIEW

**Comment by ibogicevic** [comment]
Added @danielrutz  as reviewer as he is the QA-expert

**Comment by danielrutz** [comment]
Added @ThoreKr for a second opinion on that because he is the CM Expert.

**Comment by danielrutz** [comment]
[Issue #7: Branching/Merging Concept](https://trello.com/c/1CNMgZcx/10-issue-7-branching-merging-concept)

**Comment by ThoreKr** [comment]
@danielrutz @ibogicevic updated the file

**Pull request merged**
